sudo: false
language: java
dist: precise
jdk: 
 - oraclejdk8
addons:
 apt:
  packages:
 coverity_scan:
   project:
     name: Yakindu/statecharts
   notification_email: a.muelder@googlemail.com
   build_command: mvn -f ${TRAVIS_BUILD_DIR}/releng/org.yakindu.sct.releng/pom.xml clean verify
   branch_pattern: coverity_scan
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - SWT_GTK3=0
  - DISPLAY=:99.0
  - GTEST_DIR=${TRAVIS_BUILD_DIR}/googletest-release-1.8.0/googletest
  - LIBRARY_PATH=${TRAVIS_BUILD_DIR}/googletest-release-1.8.0/googletest/build:${TRAVIS_BUILD_DIR}/googletest-release-1.8.0/googlemock/build:$LIBRARY_PATH
  - CPATH=${TRAVIS_BUILD_DIR}/googletest-release-1.8.0/googletest/include:${TRAVIS_BUILD_DIR}/googletest-release-1.8.0/googlemock/include:$CPATH
  - GMOCK_HOME
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key
  - secure: "e6AtFe0HJAHRdmzp4uXx4b+xZaEUUd2jeYiLdIkYuRa84op9iSzCmPj5uT3Vkvqps5snBrDx47Wl1EO9rl+Z91WYp1JgTT5Ek37SKj/ikhJ0HfAYBycU/MRTMO5wXEfwL29G0gjygzFxlUe7t/Y92M/VsvlEQ9nHrtqJ4hQA968="
  matrix:
  - TARGET=Neon.target
  - TARGET=Oxygen.target
  - TARGET=Photon.target
before_script:
 - wget https://github.com/google/googletest/archive/release-1.8.0.zip
 - unzip release-1.8.0.zip
 - cd googletest-release-1.8.0/googlemock
 - mkdir build && cd build && cmake .. && make
 - export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
 - cd ../../googletest
 - mkdir build && cd build && cmake .. && make
 - export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
 - cd ../..
 - export GMOCK_HOME=`pwd`
 - cd $TRAVIS_BUILD_DIR
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
script:
- cd releng/org.yakindu.sct.releng
- mvn clean verify -P$TARGET,tests
